### ISSUE TITLE
Example on how to train?

### ISSUE THREAD

**Issue by czhang96** [easonnie/combine-FEVER-NSMN#2]
Very nice work first of all! 

I know you have provided a pre-trained model and code to reproduce evaluation. Is there an example on how to repreduce the training procedure?

Thank you!

**Comment by sheenG** [comment]
its ok if u follow README. But there are some errors during my training process (I've opened an issue)

**Comment by easonnie** [comment]
@czhang96 @sheenG 
Thanks for your interests in the code and your feedbacks. I will try to come back to add a training procedure in the future when time permits.
