### ISSUE TITLE
TypeError: __call__() got an unexpected keyword argument 'cuda_device'

### ISSUE THREAD

**Issue by drfeversharedtask** [easonnie/combine-FEVER-NSMN#5]
This issue hasn't been resolved yet... I have the same issue and I followed the guidelines that were provided for solving it. I ran the code multiple times and I keep having the same problem.

Traceback (most recent call last):
File "./src/pipeline/auto_pipeline.py", line 633, in 
steps=default_steps)
File "./src/pipeline/auto_pipeline.py", line 437, in pipeline
load_from_dict=False)
File "/combine-FEVER-NSMN/src/nli/mesim_wn_simi_v1_2.py", line 2218, in pipeline_nli_run
eval_iter = biterator(dev_instances, shuffle=False, num_epochs=1, cuda_device=device_num)
TypeError: call() got an unexpected keyword argument 'cuda_device'
[INFO/MainProcess] process shutting down

**Comment by drfeversharedtask** [comment]
As a follow up: I've tried several times and the issue is still present. 
Please advise.

**Comment by easonnie** [comment]
The cuda_device is an argument only exists in the allennlp=0.7.1. See [README](https://github.com/easonnie/combine-FEVER-NSMN#requirement) for version requirements.

Python 3.6
pytorch 0.4.1
allennlp 0.7.1

**Comment by drfeversharedtask** [comment]
/combine-FEVER-NSMN$ pip show allennlp
Name: allennlp
Version: 0.7.1
All of the above versions have been verified several times. 
Have you actually tried your steps on a clean machine to confirm that going over them you'll be able to run your pipeline?

**Comment by easonnie** [comment]
I made an update on the codebase. Sorry for the confusion. Please feel free to notify me if you still have problems.

**Comment by arxivlab** [comment]
Please describe the cause of the problem. I've been trying to run your code for the past 3 weeks.

**Comment by easonnie** [comment]
@arxivlab Check out the last comment in #1.

**Comment by sheenG** [comment]
> Please describe the cause of the problem. I've been trying to run your code for the past 3 weeks.
Sir, you can refer the issue opened by me(closed now) and motify the code. Or download the new version updated by easonnie.

**Comment by sheenG** [comment]
@arxivlab 
Sir, you can refer the issue opened by me(closed now) and motify the code. Or download the new version updated by easonnie.
